### ISSUE TITLE
Make GitLab Compatible

### ISSUE THREAD

**Issue by ghost** [hotmeteor/eco-cli#2]
Not all projects are hosted on github so it would be nice if this tool could be used cross-platform

**Comment by hotmeteor** [comment]
@cole-flexsim Good call. I was also thinking of supporting Bitbucket.

**Comment by hotmeteor** [comment]
@cole-flexsim I've got a draft PR out there... untested. But if you're up for trying it out at some point, let me know. Still some work before it's usable though.

**Comment by hotmeteor** [comment]
@cole-flexsim OK, I went wild on this and essentially rewrote the package. It now uses Laravel Zero, so you'll need to run `composer install`. You may also want to back up your local `~/.eco/config.json` file, since the vault API changed a little.

Now, I haven't tested the Gitlab or Bitbucket functionality at all. I'm about to do that. But I wanted you to get at it to see if you can even get it working.

https://github.com/hotmeteor/eco-cli/pull/4

**Comment by ghost** [comment]
I thought of another situation: personally hosted servers that have GitHub, GitLab, or BitBucket. In those cases there will need to be some way to specify the base url that the repo is hosted on such as https://git.example.com

**Comment by hotmeteor** [comment]
Resolves in https://github.com/hotmeteor/eco-cli/pull/4

**Comment by hotmeteor** [comment]
@cole-flexsim This is live now!
